### ISSUE TITLE
Please modify the Sauce Labs column 'Session' from 'Selenium Web Driver'

### ISSUE THREAD

**Issue by franaiello** [dev9com/testng-webdriver#2]
I am seeing a convention from another project which has a format that seems acceptable and am hoping that this can be implemented as well.

Example: 

Scenario: SS NON-warranty serialized part repair existing CA customer

![image](https://f.cloud.github.com/assets/1959243/1450538/7475ef70-427f-11e3-886b-8b77e0bd8377.png)

**Comment by justingraham12** [comment]
Fixed in 2.1
